@extends('layouts.app')

@section('content')
    <h3>PRIVACY POLICY</h3>
    <p>Mentor Learning Services Private Limited reserve the right to store information provided by the customers who are communicating via email and this includes e-mail address of our customers, name and addresses, telephone number(s), designation etc.&nbsp; Payment information such as credit card number(s) and billing address will not be shared by Mentor Learning Services Private Limited with a third party.</p>
    <p>The information we collect can be used for internal review. They are also used to alert customers about website update and for marketing purposes. This information might be revealed to law enforcement agencies if required.</p>
    <p>We may use cookies in order to store our web visitors' preferences, to record information such as products that consumers add to their products carts and customize our web pages based on visitors' browser preferences or any other information that the visitor sends to us.</p>
    <p>The site does not share the e-mail addresses and postal addresses with any other company. However, you will receive an email campaign about the materials from us with information on latest products and services. If customers do not wish to receive such emails, they may let us know by sending us e-mail at <a href="mailto:info@mentor.in"><strong> info@mentor.in </strong></a>.</p>
    <p>We have proper security arrangements in place to protect against the loss, misuse or alteration of information that we have collected from our customers. If you find that the site is not following above stated privacy policy, you may contact us by sending us e-mail at <a href="mailto:info@mentor.in"><strong> info@mentor.in </strong></a>.</p>
    <h3>Links to other websites</h3>
    <p>Our website may contain links to other websites of interest. However, once you have used these links to leave our site, you should note that we do not have any control over the other website. Therefore, we cannot be responsible for the protection and privacy of any information which you provide whilst visiting such sites and such sites are not governed by this privacy statement. You should exercise caution and look at the privacy statement applicable to the website in question.</p>
@endsection